import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [section, setSection] = useState(['All sections', 'PHYSICS', 'CHEMISTRY', 'MATHS'])
  const [questionButtons, setQuestionButtons] = useState(['CLEAR RESPONSE', 'REVIEW', 'DUMP', 'PREVIOUS', 'NEXT'])
  const [legendButtons, setLegendButtons] = useState(['Profile', 'Instr', 'Questions', 'Submit'])
  return (
    <>
      <Head>
        <title>Online Examination System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <nav className={styles.nav}>
          <span className={styles.navtext}>
            DEMO ONLINE TEST
          </span>
        </nav>
        <div className={styles.maincontainer}>
          <div className='question-section'>
            <div className="sections-button">
              {
                section.map((sections, index) => (
                  <button key={index} className={styles.commonButton} onClick={() => console.log(index)}>{sections}</button>
                ))
              }
            </div>
            <div className={styles.questionContainer}>
              <div className={styles.questionContainerTop}>
                <span>Q No.:1</span>
                <span>View in
                  <select className={styles.selectMenu} name="question-language" id="question-language">
                    <option className={styles.selectMenu} value="volvo">English</option>
                    <option className={styles.selectMenu} value="saab">Hindi</option>
                  </select></span>

              </div>
              <div className={styles.topLine}>
                <span>QUESTION INSTRUCTION</span>
                <span>QUESTION</span>
              </div>

              <div className={styles.questionMainData}>
                <div className={styles.questionInstruction}>Here comes all instruction</div>
                <div className={styles.questionWithOptions}>
                  <div className={styles.questionDesc}>Here comes question...</div>

                  <div className={styles.inputOuter}>
                    <input type="radio" id="optionA" name="question-options" />
                    <label htmlFor="optionA"> (A). </label>
                  </div>

                  <div className={styles.inputOuter}>
                    <input type="radio" id="optionB" name="question-options" />
                    <label htmlFor="optionB"> (B). </label>
                  </div>

                  <div className={styles.inputOuter}>
                    <input type="radio" id="optionC" name="question-options" />
                    <label htmlFor="optionC"> (C). </label>
                  </div>

                  <div className={styles.inputOuter}>
                    <input type="radio" id="optionD" name="question-options" />
                    <label htmlFor="optionD"> (D). </label>
                  </div>

                </div>
              </div>
            </div>
            <div className="questionButtons">
              {
                questionButtons.map((questionButton, index) => (
                  <button key={index} className={styles.commonButton}>{questionButton}</button>
                ))
              }
            </div>
          </div>

          <div className={styles.questionStatus}>
            <div className={`${styles.commonBoxShadow} ${styles.lightBlueBackground}`}>
              <div className={styles.imageAndTime}>
                <div className={styles.candidateImage}>
                  candidate image here...
                </div>
                Time Left: <br />
                Name
              </div>

            </div>
            <div className={`${styles.commonBoxShadow} ${styles.lightBlueBackground} ${styles.questionPallete}`}>
              <div className={styles.PalleteTop}>Question Pallete</div>
              <div className={styles.palleteButtonsOuter}>
                  <div className={styles.palleteButton}>1</div>
                  <div className={styles.palleteButton}>2</div>
                  <div className={styles.palleteButton}>3</div>
                  <div className={styles.palleteButton}>4</div>
                  <div className={styles.palleteButton}>5</div>
              </div>
            </div>
            <div className={`${styles.commonBoxShadow} ${styles.lightBlueBackground} ${styles.legendOuter}`}>
              <div className={styles.legendTop}>Legend (Click to View)</div>
              <div className={styles.legendInfo}>
                <div className={styles.legendAnswer}>Answer</div>
                <div className={styles.legendNoAnswer}>No Answer</div>
                <div className={styles.legendPlusAnswer}>Review+Ans</div>
                <div className={styles.legendMinusAnswer}>Review-Ans</div>
                <div className={styles.legendDump}>Dump</div>
                <div className={styles.legendNoVisit}>No Visit</div>
              </div>
              <div className={styles.AllQuestions}>All Questions</div>
              <div className={styles.legendBottom}>
                {
                  legendButtons.map((lengendButton, index) => (
                    <button key={index} className={styles.legendButton}>{lengendButton}</button>
                  ))
                }
              </div>
            </div>
          </div>

        </div>

        <footer className={styles.footer}>
        &#169; Addmen
        </footer>
      </div>
    </>
  )
}
