import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Online Examination System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
      <nav className={styles.nav}>
        <span className={styles.navtext}>
        DEMO ONLINE TEST
        </span>
      </nav>
      <div className={styles.maincontainer}>
        <div className='question-section'>
          <div className="sections-button">
            <button className={styles.commonButton}>All sections</button>
            <button className={styles.commonButton}>PHYSICS</button>
            <button className={styles.commonButton}>CHEMISTRY</button>
            <button className={styles.commonButton}>MATHS</button>
          </div>
          <div className={styles.questionContainer}>
            <div className='question-container-top'>
              Q No.1
              View in
              <select name="question-language" id="question-language">
                <option value="volvo">English</option>
                <option value="saab">Hindi</option>
              </select>
            </div>
            <div className='top-line'>
              QUESTION INSTRUCTION
              QUESTION
            </div>
            <div className={styles.questionMainData}>
              <div className='question-instruction'>Here comes all instruction</div>
              <div className='question-with-options'>
                Here comes question...
                <input type="radio" id="optionA" name="question-options" />
                <label for="optionA"> (A). </label>
                <input type="radio" id="optionB" name="question-options" />
                <label for="optionB"> (B). </label>
                <input type="radio" id="optionC" name="question-options" />
                <label for="optionC"> (C). </label>
                <input type="radio" id="optionD" name="question-options" />
                <label for="optionD"> (D). </label>
              </div>
            </div>
          </div>
          <div className="question-buttons">
          <button className={styles.commonButton}>CLEAR RESPONSE</button>
            <button className={styles.commonButton}>REVIEW</button>
            <button className={styles.commonButton}>DUMP</button>
            <button className={styles.commonButton}>PREVIOUS</button>
            <button className={styles.commonButton}>NEXT</button>
          </div>
        </div>

        <div className={styles.questionStatus}>
          <div className={styles.commonBoxShadow}>
            <div className="candidate-image">
              candidate image here... 
            </div>
              Time and Name
          </div>
          <div className={styles.commonBoxShadow}>
            <div className="pallete-top">Question Pallete</div>
            <div className='pallete-buttons'>

            </div>
          </div>
          <div className={styles.commonBoxShadow}>
            <div className="legend-top">Legend (Click to View)</div>
            <div className="legend-info">
              <div>Answer</div>
              <div>No Answer</div>
              <div>Review Answer</div>
              <div>Review Answer</div>
              <div>Dump</div>
              <div>No Visit</div>
              <div>All Questions</div>
            </div>
            <div className="legend-bottom">
            <button className={styles.commonButton}>Profile</button>
            <button className={styles.commonButton}>Instr</button>
            <button className={styles.commonButton}>Questions</button>
            <button className={styles.commonButton}>Submit</button>
            </div>
          </div>
        </div>

      </div>

      <footer className={styles.footer}>
          Addmen
      </footer>
      </div>
    </>
  )
}
